[project]
name="pythonripper"
dynamic=["version"]
description="A script collection that can download stuff from different hosting sites and update your downloaded copy with new files."
authors=[{name="TheTimebreaker"}]
readme="README.md"
requires-python=">=3.14"
dependencies = [
  "aiofiles>=25.1.0",
  "aioshutil>=1.6",
  "asynciolimiter>=1.2.0",
  "asyncstdlib>=3.14.0",
  "bs4>=0.0.2",
  "curl-cffi>=0.16.3",
  "duplicate_image_finder @ https://github.com/TheTimebreaker/duplicate_image_finder/releases/download/v2.0.3/duplicate_image_finder-2.0.3-py3-none-any.whl",
  "httpx>=0.28.1",
  "psd-tools>=1.19.0",
  "requests>=2.34.2",
  "selenium>=4.48.0",
  "wget>=3.2",
  "xmltodict>=1.0.4",
]

[dependency-groups]
dev = [
    "black~=26.5.1",
    "mypy~=2.1.0",
    "ruff~=0.15.17",
    "types-aiofiles>=25.1.0.20260518",
    "types-requests>=2.33.0.20260712",
    "types-send2trash>=2.1.0.20260408",
    "types-xmltodict>=1.0.1.20260518",
]

[tool.ruff]
line-length = 150
target-version = "py314"

exclude = [
  ".venv",
  "build",
  "dist",
  "__pycache__",
  "__init__.py",
  "test*.*",
]

[tool.ruff.lint]
select = [
  "E",   # pycodestyle (errors)
  "F",   # pyflakes
  "I",   # isort (import sorting)
  "B",   # flake8-bugbear (extra checks for likely bugs)
  "UP",  # pyupgrade (modern Python syntax suggestions)
  "N",   # pep8-naming
  "ERA", # Mark commented out code
  "ANN", # Some type annotations
  "ASYNC", # Async checks
  "FIX",
  "ISC", # implicit str concat
  "ICN", # import conventions
  "G", #Logging format
  "INP", #implicit-no-pep420
  "PIE",
  "Q", #flake8-quotes
  "TD", #TODOs,
  "ARG", #Unused args
  "RUF", #Ruff specifics
]
extend-select = ["N815", "N816"]

ignore = [
  "ANN401", #allow type:Any
  "TD003", #Missing issue link for TODO
]

[tool.pylint."MASTER"]
disable = ["all"]
enable = [
  "W1203", #fstring in logging
  "C0103", #invalid name
]
ignore-paths = [".venv", ".venv-windows", ".venv-linux", "test*.*"]


[tool.black]
line-length = 150
target-version = ["py314"]

[tool.mypy]
python_version = "3.14"
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_any_generics = true
check_untyped_defs = true
warn_unused_ignores = true
warn_return_any = true
exclude = ["test*.*", ".venv", ".venv-windows", ".venv-linux"]


[[tool.mypy.overrides]]
module = [
  "easygui",
  "pyperclip",
  "wget",
  "ratelimit",
  "html_to_json",
  "asynciolimiter",
  "bs4",
  "ffmpeg",
  "psd_tools",
  "plyer",
  "ciso8601",
  "httpx",
  "curl_cffi"
]
ignore_missing_imports = true
